# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whoWOoUEuMMvhLbhstCK3tI3z9U-lU-v

Bài 1:
"""

a = int(input("Nhập số a: "))
b = int(input("Nhập số b: "))

# a cộng b
print("a + b =", a + b)

# a trừ b
print("a - b =", a - b)

# a nhân b
print("a * b =", a * b)

# a chia lấy nguyên b
print("a // b =", a // b)

# a mũ b
print("a ** b =", a ** b)

# a chia dư b
print("a % b =", a % b)

# so sánh a và b
if a > b:
    print("a lớn hơn b")
elif a < b:
    print("a nhỏ hơn b")
else:
    print("a bằng b")

# a AND b
print("a AND b =", a & b)

# a OR b
print("a OR b =", a | b)

# a XOR b
print("a XOR b =", a ^ b)

# NOT a == b
print("NOT a == b =", not (a == b))

# a dịch phải 5 bit
print("a dịch phải 5 bit =", a >> 5)

# a dịch trái 6 bit
print("a dịch trái 6 bit =", a << 6)

# in hệ cơ số 2 đảo ngược của a
print("Hệ cơ số 2 đảo ngược của a:", bin(a)[:1:-1])

"""Bài 2:"""

char = input()
if "hit" or "HIT" in char:
    print("True")
else:
    print ("false")

if "14" not in char:
  print ("True")
else:
  print (" false")

"""Bài 3:"""

for i in range(20):
  print("I’m HIT 14")

"""Bài 4:"""

a = int(input("Nhập số a: "))
bit_count = a.bit_length()
print("Số bits cần thiết để biểu diễn a:", bit_count)

a = 10
print(dir(a))